### PR TITLE
Update for 1.18 chunk and light packets

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
Can you 
1. Use it to extract 1.18 chunks
2. Put the output in a prismarine-chunk 1.18 PR
3. Send the link to that PR here ?
That will allow checking that it works

**Comment by rom1504** [comment]
I guess if the tests were testing multiple versions here it wouldn't hurt hmm

**Comment by nickelpro** [comment]
Is this expected to support multiple versions? The current architecture of chunk dumper doesn't account for version, my understanding of the code is it will only ever support the latest version

**Comment by rom1504** [comment]
Yes thanks to a bunch of if and the way undefined works with objects in js

**Comment by rom1504** [comment]
We should add all the versions to the CI to confirm though
But pretty sure it works for all versions post 1.8

**Pull request merged**
